package cn.caoler.model;

import cn.caoler.model.base.BaseCar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Car extends BaseCar<Car> {
	public static final Car dao = new Car().dao();
}
