package cn.caoler.model;

import cn.caoler.model.base.BaseTicket;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ticket extends BaseTicket<Ticket> {
	public static final Ticket dao = new Ticket().dao();
}
