package cn.caoler.model;

import cn.caoler.model.base.BaseWiring;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Wiring extends BaseWiring<Wiring> {
	public static final Wiring dao = new Wiring().dao();
}
