package cn.caoler.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_admin", "id", Admin.class);
		arp.addMapping("t_car", "class", Car.class);
		arp.addMapping("t_ticket", "price", Ticket.class);
		arp.addMapping("t_user", "id", User.class);
		arp.addMapping("t_wiring", "start", Wiring.class);
	}
}

